version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.7
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./acme.json:/traefik.json
      - ./traefik.log:/traefik.log

  database:
    image: mysql:8
    restart: always
    labels:
      - traefik.enable=false
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=intalnet
    ports:
      - 3306:3306
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  api:
    image: nestorsanchezz/intalnet_api:latest
    restart: always
    labels:
      - traefik.http.routers.intalnet-api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.intalnet-api.tls.certresolver=myresolver
    depends_on:
      - database
      - reverse-proxy
    environment:
      - DB_HOST=database
      - DB_NAME=intalnet
    env_file:
      - .env
      - .api.env

  frontend:
    image: nestorsanchezz/intalnet_frontend:latest
    restart: always
    labels:
      - traefik.http.routers.intalnet-frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.intalnet-frontend.tls.certresolver=myresolver
      - traefik.http.routers.intalnet-frontend.rule=(Host(`intalnettelecomunicaciones.com`) || Host(`www.intalnettelecomunicaciones.com`))
    depends_on:
      - api

volumes:
  dbdata:
